### ISSUE TITLE
Publish extension on Open VSX

### ISSUE THREAD

**Issue by x1h0** [grafana/vscode-jsonnet#15]
Hi there,

Thanks for this useful extension. I would like to ask you to kindly consider publishing this extension to the Open VSX marketplace.
I mainly use [Gitpod](https://www.gitpod.io/), and so could use the extension there as well. That would be great.

### Context
Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of .vsix files from it. I kindly ask that you publish this extension on Open VSX, to use VS Code extensions in non-Microsoft products.

### What is Open VSX? Why does it exist?
Open VSX is a vendor neutral alternative at the Eclipse Foundation to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io/), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

### How can you publish to Open VSX?
The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the process with an example GitHub Action workflow.

**Comment by julienduchesne** [comment]
On it! I've submitted the namespace, waiting for it to be linked to my user

**Comment by julienduchesne** [comment]
Done! https://open-vsx.org/extension/Grafana/vscode-jsonnet
