### ISSUE TITLE
`.jsonnet` files are being recognized as JavaScript files

### ISSUE THREAD

**Issue by hwittenborn** [grafana/vscode-jsonnet#18]
See the following:

![image](https://user-images.githubusercontent.com/74838472/188529623-383d30e8-5c47-46d9-8eb4-61d0f6780fd3.png)

No clue why it might be happening, I've tried restarting VS Code but it didn't fix anything.

**Comment by julienduchesne** [comment]
Check if you have a `files.associations` setting in your workspace or global settings. Perhaps a `*.js*` association to the javascript language identifier

**Comment by hwittenborn** [comment]
Looks like I had `.jsonnet` set to `javascript` in my config for some reason, I don't remember setting it like that though :P. Anyway, everything's working now, thanks!
