### ISSUE TITLE
Republish as `grafana`

### ISSUE THREAD

**Issue by julienduchesne** [grafana/vscode-jsonnet#2]
This is currently published under my personal account. We should republish this from a Grafana Azure account

**Comment by aaronjheng** [comment]
Maybe with a good `icon` and `displayName`. :)

**Comment by julienduchesne** [comment]
I republished it under a `Grafana` account: https://marketplace.visualstudio.com/items?itemName=Grafana.vscode-jsonnet. Unfortunately, the ID of the extension changed so to get new versions (when they will exist), you will need to uninstall the current version and reinstall it. The configs are all mapped the same though
