### ISSUE TITLE
Odd auto formatting

### ISSUE THREAD

**Issue by goodspark** [grafana/vscode-jsonnet#20]
If I create a jsonnet file with:
```jsonnet
local asd(
  x=1
) = {
  hello: x,
};
asd(x=4)
```

It gets auto-formatted to:
```jsonnet
local asd(
  x=1
      ) = {
  hello: x,
};
asd(x=4)
```

Which is really weird.

Version: 0.3.1

**Comment by julienduchesne** [comment]
This is unfortunately an issue with the native jsonnet formatter: 

```console
$ echo "local asd(
  x=1
) = {
  hello: x,
};
asd(x=4)" | jsonnetfmt -

local asd(
  x=1
      ) = {
  hello: x,
};
asd(x=4)
```

An issue here: https://github.com/google/go-jsonnet would be better targeted

**Comment by goodspark** [comment]
Ah, OK. Thanks! I'll file an issue there.
