### ISSUE TITLE
Is formatter configurable?

### ISSUE THREAD

**Issue by shinebayar-g** [grafana/vscode-jsonnet#21]
It keeps replacing my 4 indent code to 2 indent. How can I configure it?

**Comment by julienduchesne** [comment]
Add the following setting in your settings.json file
![image](https://user-images.githubusercontent.com/29210090/195231403-86417e15-4383-4ce0-8bbe-86df8a0c27af.png)

**Comment by julienduchesne** [comment]
You can also use autocomplete to find all the options: 
![image](https://user-images.githubusercontent.com/29210090/195231463-d3fca500-b874-4abc-a6c7-9c052ce3e364.png)
