### ISSUE TITLE
How to format jsonnet code?

### ISSUE THREAD

**Issue by mkmik** [grafana/vscode-jsonnet#5]
The README mentions that it can format code; however it doesn't appear to format the code by default nor can I find a setting to turn on code formatting.

**Comment by julienduchesne** [comment]
🤔 . These are my settings to format on save:
```
    "files.autoSave": "onFocusChange",
    "editor.formatOnSave": true,
    "[jsonnet]": {
        "editor.defaultFormatter": "Grafana.vscode-jsonnet"
     },
```

**Comment by mkmik** [comment]
thanks! Adding this did the trick:

```
  "[jsonnet]": {
        "editor.defaultFormatter": "Grafana.vscode-jsonnet"
     },
```

Why is this not enabled by default?

**Comment by julienduchesne** [comment]
> thanks! Adding this did the trick:
> 
> ```
>   "[jsonnet]": {
>         "editor.defaultFormatter": "Grafana.vscode-jsonnet"
>      },
> ```
> 
> Why is this not enabled by default?

You may have two different jsonnet formatters installed and vscode is having trouble figure out which to use

**Comment by mkmik** [comment]
I think I had the old vscode-jsonnet extension before you renamed it into the "grafana" org.
