### ISSUE TITLE
How does formatting works?

### ISSUE THREAD

**Issue by darox** [grafana/vscode-jsonnet#8]
How can the formatting feature be triggered? It seems not working in my case. Linting and error indication are working. Thank you!

**Comment by leejones** [comment]
I had the same question and discovered 2 ways to run the formatter:

**On demand:** Go to `View -> Command Palette`. Type `Format` to limit results. Click `Format Document`:

<img width="793" alt="Screen Shot 2022-05-11 at 4 21 00 PM" src="https://user-images.githubusercontent.com/25408/167949746-30838b14-85d8-4e9a-b685-b90a5d6ce5a2.png">


**Automatically on save:** Go to the global settings for VS Code and search for `Format`. Enable `Editor: Format On Save`:

<img width="1520" alt="Screen Shot 2022-05-11 at 4 22 18 PM" src="https://user-images.githubusercontent.com/25408/167949987-15e8382b-2cac-4729-a09c-a7218ea2a967.png">

**Comment by darox** [comment]
@leejones  Wow, thank you!
