### ISSUE TITLE
autocomplete for imports

### ISSUE THREAD

**Issue by iFrozenPhoenix** [grafana/vscode-jsonnet#9]
## Environment
go-jsonnet: 0.18.0
jsonnet-language-server: 0.2.3

## Current behaviour
When importing a jsonnet file and trying to use it, no autocompletion is provided for the import.

## Expected behaviour
After importing a jsonnet file autocompletion is provided for the import, i.e. when pressing the dot key after "im" ident in the example.

## Example
test.jsonnet
```jsonnet
{
    name: "test"
}
```

main.jsonnet
```jsonnet
local im = import "./test.jsonnet";

{
    asd: im.name
}
```
output
```
{
    "asd": "test"
}
```

**Comment by julienduchesne** [comment]
Will be tracked here: https://github.com/grafana/jsonnet-language-server/issues/5. I have added autocomplete support for `self` and locals so far. Imports will happen in october probably
